-- MySQL Script generated by MySQL Workbench
-- Tue Sep 27 14:23:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tutorsDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tutorsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tutorsDB` DEFAULT CHARACTER SET utf8 ;
USE `tutorsDB` ;

-- -----------------------------------------------------
-- Table `tutorsDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorsDB`.`users` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(15) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `is_admin` BIT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorsDB`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorsDB`.`tutors` (
  `tutor_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `midname` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `about_self` VARCHAR(1000) NULL,
  `photo` BLOB NULL,
  PRIMARY KEY (`tutor_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `tutorsDB`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorsDB`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorsDB`.`subjects` (
  `subject_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorsDB`.`tutor_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorsDB`.`tutor_subject` (
  `tutor_subject_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `tutor_id_idx` (`tutor_subject_id` ASC) VISIBLE,
  CONSTRAINT `tutor_id`
    FOREIGN KEY (`tutor_subject_id`)
    REFERENCES `tutorsDB`.`tutors` (`tutor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`tutor_subject_id`)
    REFERENCES `tutorsDB`.`subjects` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
